# Generated by Django 2.2.13 on 2021-06-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('create_time', models.CharField(max_length=120)),
                ('gs_a1', models.TextField(max_length=120)),
                ('gs_a2', models.TextField(max_length=120)),
                ('gs_a3', models.TextField(max_length=120)),
                ('gs_a4', models.TextField(max_length=120)),
                ('gs_b1', models.TextField(max_length=120)),
                ('gs_b2', models.TextField(max_length=120)),
                ('gs_b3', models.TextField(max_length=120)),
                ('gs_b4', models.TextField(max_length=120)),
                ('gs_c1', models.TextField(max_length=120)),
                ('gs_c2', models.TextField(max_length=120)),
                ('gs_c3', models.TextField(max_length=120)),
                ('gs_c4', models.TextField(max_length=120)),
                ('gs_d1', models.TextField(max_length=120)),
                ('gs_d2', models.TextField(max_length=120)),
                ('gs_d3', models.TextField(max_length=120)),
                ('gs_d4', models.TextField(max_length=120)),
                ('gs_e1', models.TextField(max_length=120)),
                ('gs_e2', models.TextField(max_length=120)),
                ('gs_e3', models.TextField(max_length=120)),
                ('gs_e4', models.TextField(max_length=120)),
                ('gs_f1', models.TextField(max_length=120)),
                ('gs_f2', models.TextField(max_length=120)),
                ('gs_f3', models.TextField(max_length=120)),
                ('gs_f4', models.TextField(max_length=120)),
                ('btf_1', models.TextField(max_length=120)),
                ('btf_2', models.TextField(max_length=120)),
                ('btf_3', models.TextField(max_length=120)),
                ('btf_4', models.TextField(max_length=120)),
                ('btf_l1', models.TextField(max_length=120)),
                ('btf_l2', models.TextField(max_length=120)),
                ('ks16_aw', models.TextField(max_length=120)),
                ('ks16_al', models.TextField(max_length=120)),
                ('ks16_bw', models.TextField(max_length=120)),
                ('ks16_bl', models.TextField(max_length=120)),
                ('ks16_cw', models.TextField(max_length=120)),
                ('ks16_cl', models.TextField(max_length=120)),
                ('ks16_dw', models.TextField(max_length=120)),
                ('ks16_dl', models.TextField(max_length=120)),
                ('ks16_ew', models.TextField(max_length=120)),
                ('ks16_el', models.TextField(max_length=120)),
                ('ks16_fw', models.TextField(max_length=120)),
                ('ks16_fl', models.TextField(max_length=120)),
                ('ks16_gw', models.TextField(max_length=120)),
                ('ks16_gl', models.TextField(max_length=120)),
                ('ks16_hw', models.TextField(max_length=120)),
                ('ks16_hl', models.TextField(max_length=120)),
                ('ks8_aw', models.TextField(max_length=120)),
                ('ks8_al', models.TextField(max_length=120)),
                ('ks8_bw', models.TextField(max_length=120)),
                ('ks8_bl', models.TextField(max_length=120)),
                ('ks8_cw', models.TextField(max_length=120)),
                ('ks8_cl', models.TextField(max_length=120)),
                ('ks8_dw', models.TextField(max_length=120)),
                ('ks8_dl', models.TextField(max_length=120)),
                ('ks4_aw', models.TextField(max_length=120)),
                ('ks4_al', models.TextField(max_length=120)),
                ('ks4_bw', models.TextField(max_length=120)),
                ('ks4_bl', models.TextField(max_length=120)),
                ('final_l', models.TextField(max_length=120)),
                ('winner', models.TextField(max_length=120)),
            ],
        ),
    ]
